export const dataFilms = [
  {
    id: 1,
    image: '/img/film1.jpg',
    title: 'Born To Fly',
    year: '2022',
    nation: 'Korea',
    price: 99,
    desc: 'A special operations team headed by elite pilots are ordered to test new fighter jets. Test flight after test flight, they challenge the limits of the sky and themselves.',
  },
  {
    id: 2,
    image: '/img/film2.jpg',
    title: 'Forrest Gump',
    year: '2023',
    nation: 'USA',
    price: 99,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia laudantium numquam quia quaerat, reiciendis porro nemo possimus qui. Odio, debitis!',
  },
  {
    id: 3,
    image: '/img/film3.jpg',
    title: 'The Shawshank Redemption',
    year: '1984',
    nation: 'Viet Nam',
    price: 99,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia laudantium numquam quia quaerat, reiciendis porro nemo possimus qui. Odio, debitis!',
  },
  {
    id: 4,
    image: '/img/film4.jpg',
    title: 'The Godfather',
    year: '1990',
    nation: 'Thailand',
    price: 99,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia laudantium numquam quia quaerat, reiciendis porro nemo possimus qui. Odio, debitis!',
  },
  {
    id: 5,
    image: '/img/film5.jpg',
    title: 'The Dark Knight',
    year: '1989',
    nation: 'Campuchia',
    price: 99,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia laudantium numquam quia quaerat, reiciendis porro nemo possimus qui. Odio, debitis!',
  },
  {
    id: 6,
    image: '/img/film6.jpg',
    title: '"Pulp Fiction',
    year: '2010',
    nation: 'Laos',
    price: 99,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia laudantium numquam quia quaerat, reiciendis porro nemo possimus qui. Odio, debitis!',
  },
  {
    id: 7,
    image: '/img/film7.jpg',
    title: 'Schindler List',
    year: '2002',
    nation: 'Japanse',
    price: 99,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia laudantium numquam quia quaerat, reiciendis porro nemo possimus qui. Odio, debitis!',
  },
  {
    id: 8,
    image: '/img/film8.jpg',
    title: 'Inception',
    year: '2004',
    nation: 'France',
    price: 99,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia laudantium numquam quia quaerat, reiciendis porro nemo possimus qui. Odio, debitis!',
  },
  {
    id: 9,
    image: '/img/film9.jpg',
    title: 'The Matrix',
    year: '2009',
    nation: 'Japanse',
    price: 99,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia laudantium numquam quia quaerat, reiciendis porro nemo possimus qui. Odio, debitis!',
  },
];
